language: node_js
node_js:
  - '10'
  - '8'

before_install:
  - npm install -g codecov

script:
  - yarn run check
  - yarn run build
  - codecov

cache: yarn

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
